### ISSUE TITLE
incompatible with Python 3.5

### ISSUE THREAD

**Issue by garretwilson** [jefftriplett/kindlestrip#2]
Doesn't seem to work with Python 3.5.

> SyntaxError: Missing parentheses in call to 'print'

**Comment by JackChen007** [comment]
`D:\mydoc\calibre\calibre\The Economist (187)>kindlestrip "The Economist - calibre.mobi" "The Economist - strip.mobi"
Traceback (most recent call last):
  File "c:\users\shihang\appdata\local\programs\python\python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\shihang\appdata\local\programs\python\python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\ShiHang\AppData\Local\Programs\Python\Python36-32\Scripts\kindlestrip.exe\__main__.py", line 5, in <module>
  File "c:\users\shihang\appdata\local\programs\python\python36-32\lib\site-packages\kindlestrip.py", line 70
    print "Warning: pathof expects utf-8 encoded byestring: ", s
                                                            ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Warning: pathof expects utf-8 encoded byestring: ", s)?`

Also not work on Python 3.5 .

**Comment by cxumol** [comment]
I've ported it to python 3 version, and it works well on my machine (python 3.6.6). 
pls check out https://github.com/jefftriplett/kindlestrip/pull/3

**Comment by yhh2021** [comment]
This script is written for Python 2.

**Comment by jefftriplett** [comment]
Long time to update but we are current with Python 3.10 to 3.14 now.
